version: "3.8"

services:
  server:
    build:
      context: ./server
    restart: unless-stopped
    ports:
      - "9030:9030"
    environment:
      - LOGIN_USER=your_username
      - LOGIN_PASS=your_password
      - ESP32_URL=http://192.168.1.XXX # Replace with your ESP32 URL
      - JWT_SECRET=your_jwt_secret
    networks:
      - homecamnet

  client:
    build:
      context: ./client
    restart: unless-stopped
    ports:
      - "9031:9031"
    depends_on:
      - server
    environment:
      - VITE_API_URL=/backend
      - NODE_ENV=production
    networks:
      - homecamnet

networks:
  homecamnet:
    driver: bridge
